// ════════════════════════════════════════════════════════════════════════
// Petit corpus de noms de papillons — POUR LES DÉMOS LIVE DU DECK (navigateur)
// ════════════════════════════════════════════════════════════════════════
// Le vrai entraînement (`vp run train`) lit le corpus complet (~5 904 noms) via
// `getAllDocs()` → `node:fs`. Indisponible côté navigateur. On embarque donc ici
// un ÉCHANTILLON RÉEL (extrait de `data/butterflies/french.refined.txt`), assez
// petit pour entraîner un mini-modèle en quelques secondes dans une slide.
//
// On garde ce corpus DANS le deck (pas dans `microgpt-ts`) : suivre le choix de
// l'auteur de ne pas faire fuiter une commodité de démo dans le package « essence »
// (cf. apps/demos/src/dataset/sample.ts). La donnée est PASSÉE en paramètre aux
// fabriques (`makeTokenizer(docs)`, boucle d'entraînement) — jamais lue globalement.
export const BUTTERFLY_DOCS: readonly string[] = [
  "amiral",
  "atalante",
  "bien-aimée",
  "bleu arctique",
  "bleu des lupins",
  "bleu mélissa",
  "bleu nordique",
  "grand cuivré",
  "grand coliade",
  "grand faune",
  "grande violette",
  "flambeau nacré",
  "flocon de laine",
  "faux casque",
  "faux-mars",
  "sablé basque",
  "safrané",
  "soufré jumeau",
  "agreste serbe",
  "agreste crétois",
  "alpin commun",
  "alpin boréal",
  "alpin rougeâtre",
  "alpin à bandes",
  "ambré",
  "agréable",
  "asopie brûlée",
  "boarmie tigrée",
  "bois veiné",
  "cidarie fauve",
  "gnophos obscure",
  "gnophos helvète",
  "gnophos ambiguë",
  "larentie lavée",
  "horisme jumeau",
  "agrotide hastée",
  "acidalie sobre",
  "acidalie grêle",
  "acidalie naine",
  "acidalie ornée",
  "acidalie pâle",
  "adèle australe",
  "adèle cuivrée",
  "alchimiste",
  "anachorète",
  "campion",
  "infidèle",
  "intruse",
  "javelot",
  "jason",
  "flammèche",
  "demi-deuil",
  "grande coronide",
  "petite violette",
  "moyen nacré",
  "tristan",
  "myrtil",
  "amaryllis",
  "aurore",
  "citron",
  "céphale",
  "mégère",
  "satyre",
  "morio",
  "robert-le-diable",
  "vulcain",
];
